# Makefile for mytpbig.exe
#   generated by ATP Launcher
IMAGE  = C:/ATP/MeuTpbig/mytpbig.exe
CC = gcc.exe
FOR= g77.exe
OBJECTS = dimdef.o \
          newmods.o \
          comtac.o \
          fgnmod.o \
          usernl.o \
          analyt.o \
          devt69.o \
          hopcod.o \
          usrfun.o \
          user10.o
INSFILE = blkcom.ins \
          comta1.ins \
          comta2.ins \
          comta3.ins \
          dekspy.ins \
          tacsar.ins \
          space2.ins
CFLAGS = -DUNDERSCORE -O2
FFLAGS = -O2
LIBRARY = C:/ATP/atpmingw/make/tpbig.a C:/ATP/atpmingw/make/dismg7.a -lgdi32 \
	-L"C:/ATP/atpmingw/make/MinGW/bin/../lib"
all:	$(IMAGE)
.f.o:
	$(FOR) -c $(FFLAGS) $<
.c.o:
	$(CC) -c $(CFLAGS) $<
$(IMAGE) : $(OBJECTS) $(INSFILE)
	copy "C:\ATP\atpmingw\make\MinGW\bin\..\lib\crt2.o"
	$(FOR) -s -o $(IMAGE) $(OBJECTS) $(LIBRARY)
	del crt2.o
